In [1]:
import pandas as pd
import geopandas as gpd
import glob

In [2]:
comptage_routier_gdf = gpd.read_file("../raw/referentiel-comptages-routiers.geojson")
iris_gdf = gpd.read_file("../raw/iris_raw_20260427.geojson")
comptage_routier_gdf["iu_ac"]=pd.to_numeric(comptage_routier_gdf["iu_ac"])

In [5]:
files = glob.glob("../raw/trafic/2025/*.txt")

df_list = [pd.read_csv(f, sep=";") for f in files]
trafic_df = pd.concat(df_list, ignore_index=True)

In [6]:
trafic_df.head()

,iu_ac,libelle,iu_nd_amont,libelle_nd_amont,iu_nd_aval,libelle_nd_aval,t_1h,q,k,etat_trafic,etat_barre,dessin
0,799,Bd_Kellermann,460,Bd_Kellermann-Moulin_Pointe,459,Bd_Kellermann-Damesme,2025-01-01 01:00:00,127.0,NaN,0,3,"""<PLINE COURBE=""""1""""><PT X=""""601352"""" Y=""""1245..."
1,799,Bd_Kellermann,460,Bd_Kellermann-Moulin_Pointe,459,Bd_Kellermann-Damesme,2025-01-01 02:00:00,175.0,NaN,0,3,"""<PLINE COURBE=""""1""""><PT X=""""601352"""" Y=""""1245..."
2,799,Bd_Kellermann,460,Bd_Kellermann-Moulin_Pointe,459,Bd_Kellermann-Damesme,2025-01-01 03:00:00,180.0,NaN,0,3,"""<PLINE COURBE=""""1""""><PT X=""""601352"""" Y=""""1245..."
3,799,Bd_Kellermann,460,Bd_Kellermann-Moulin_Pointe,459,Bd_Kellermann-Damesme,2025-01-01 04:00:00,141.0,NaN,0,3,"""<PLINE COURBE=""""1""""><PT X=""""601352"""" Y=""""1245..."
4,799,Bd_Kellermann,460,Bd_Kellermann-Moulin_Pointe,459,Bd_Kellermann-Damesme,2025-01-01 05:00:00,125.0,NaN,0,3,"""<PLINE COURBE=""""1""""><PT X=""""601352"""" Y=""""1245..."

In [7]:
comptage_routier_gdf.head()

,iu_ac,date_debut,date_fin,libelle,iu_nd_aval,libelle_nd_aval,iu_nd_amont,libelle_nd_amont,geo_point_2d,geometry
0,7023,2017-06-28 02:00:00+00:00,2023-01-01 01:00:00+00:00,Bd_Macdonald,931,Macdonald-Canal,932,Macdonald_Prefecture,"{'lon': 2.3832756391563334, 'lat': 48.89891176...","LINESTRING (2.38368 48.89883, 2.38287 48.89899)"
1,1479,1996-10-03 02:00:00+00:00,2023-01-01 01:00:00+00:00,Bd_Serurier,785,Bd_Serurier-Robert_Debre,786,Serurier-Algerie-Pre_St_Gervais,"{'lon': 2.402381696377139, 'lat': 48.878440148...","LINESTRING (2.40167 48.87867, 2.40264 48.87834..."
2,1165,1996-10-03 02:00:00+00:00,2023-01-01 01:00:00+00:00,Pte_de_Vanves,588,Pte_de_Vanves,647,Place_de_la_Porte_de_Vanves,"{'lon': 2.3051155095620137, 'lat': 48.82730831...","LINESTRING (2.30486 48.82706, 2.30537 48.82756)"
3,1445,1996-10-03 02:00:00+00:00,2023-01-01 01:00:00+00:00,Av_Pte_de_Montreuil,769,Bd_Davout-Avron-Pte_Montreuil,770,Pl_Pte_Montreuil-Av_Pte_Montreui,"{'lon': 2.411845651868501, 'lat': 48.853801860...","LINESTRING (2.41293 48.85399, 2.41076 48.85361)"
4,5198,1996-10-25 02:00:00+00:00,2023-01-01 01:00:00+00:00,Place_Pte_Champerret,2748,Pl_Stuart_Merrill,2739,Champerret-Somme,"{'lon': 2.290218249525719, 'lat': 48.885777089...","LINESTRING (2.28918 48.88591, 2.29125 48.88564)"

In [8]:
trafic_arcs = trafic_df.merge(comptage_routier_gdf,on="iu_ac",how="inner")

In [9]:
trafic_arcs.head()

,iu_ac,libelle_x,iu_nd_amont_x,libelle_nd_amont_x,iu_nd_aval_x,libelle_nd_aval_x,t_1h,q,k,etat_trafic,...,dessin,date_debut,date_fin,libelle_y,iu_nd_aval_y,libelle_nd_aval_y,iu_nd_amont_y,libelle_nd_amont_y,geo_point_2d,geometry
0,799,Bd_Kellermann,460,Bd_Kellermann-Moulin_Pointe,459,Bd_Kellermann-Damesme,2025-01-01 01:00:00,127.0,NaN,0,...,"""<PLINE COURBE=""""1""""><PT X=""""601352"""" Y=""""1245...",1996-10-03 02:00:00+00:00,2023-01-01 01:00:00+00:00,Bd_Kellermann,459,Bd_Kellermann-Damesme,460,Bd_Kellermann-Moulin_Pointe,"{'lon': 2.3552584484462633, 'lat': 48.82090579...","LINESTRING (2.35584 48.82067, 2.35515 48.82097..."
1,799,Bd_Kellermann,460,Bd_Kellermann-Moulin_Pointe,459,Bd_Kellermann-Damesme,2025-01-01 02:00:00,175.0,NaN,0,...,"""<PLINE COURBE=""""1""""><PT X=""""601352"""" Y=""""1245...",1996-10-03 02:00:00+00:00,2023-01-01 01:00:00+00:00,Bd_Kellermann,459,Bd_Kellermann-Damesme,460,Bd_Kellermann-Moulin_Pointe,"{'lon': 2.3552584484462633, 'lat': 48.82090579...","LINESTRING (2.35584 48.82067, 2.35515 48.82097..."
2,799,Bd_Kellermann,460,Bd_Kellermann-Moulin_Pointe,459,Bd_Kellermann-Damesme,2025-01-01 03:00:00,180.0,NaN,0,...,"""<PLINE COURBE=""""1""""><PT X=""""601352"""" Y=""""1245...",1996-10-03 02:00:00+00:00,2023-01-01 01:00:00+00:00,Bd_Kellermann,459,Bd_Kellermann-Damesme,460,Bd_Kellermann-Moulin_Pointe,"{'lon': 2.3552584484462633, 'lat': 48.82090579...","LINESTRING (2.35584 48.82067, 2.35515 48.82097..."
3,799,Bd_Kellermann,460,Bd_Kellermann-Moulin_Pointe,459,Bd_Kellermann-Damesme,2025-01-01 04:00:00,141.0,NaN,0,...,"""<PLINE COURBE=""""1""""><PT X=""""601352"""" Y=""""1245...",1996-10-03 02:00:00+00:00,2023-01-01 01:00:00+00:00,Bd_Kellermann,459,Bd_Kellermann-Damesme,460,Bd_Kellermann-Moulin_Pointe,"{'lon': 2.3552584484462633, 'lat': 48.82090579...","LINESTRING (2.35584 48.82067, 2.35515 48.82097..."
4,799,Bd_Kellermann,460,Bd_Kellermann-Moulin_Pointe,459,Bd_Kellermann-Damesme,2025-01-01 05:00:00,125.0,NaN,0,...,"""<PLINE COURBE=""""1""""><PT X=""""601352"""" Y=""""1245...",1996-10-03 02:00:00+00:00,2023-01-01 01:00:00+00:00,Bd_Kellermann,459,Bd_Kellermann-Damesme,460,Bd_Kellermann-Moulin_Pointe,"{'lon': 2.3552584484462633, 'lat': 48.82090579...","LINESTRING (2.35584 48.82067, 2.35515 48.82097..."

In [10]:
trafic_arcs = gpd.GeoDataFrame(
    trafic_arcs,
    geometry="geometry",
    crs=comptage_routier_gdf.crs
)

In [11]:
trafic_arcs = trafic_arcs[["iu_ac","t_1h","q","k","etat_trafic","etat_barre","geometry"]]

In [12]:
iris_gdf = iris_gdf.to_crs(comptage_routier_gdf.crs)

In [13]:
comptage_routier_gdf["geometry"]=comptage_routier_gdf.geometry.representative_point()

In [14]:
arcs_arrondissements = gpd.sjoin(
    comptage_routier_gdf,
    iris_gdf,
    how="inner",
    predicate="within"
)

In [15]:
arcs_arrondissements = arcs_arrondissements[[
    "iu_ac",
    "geometry",
    "code_iris",
    "nom_iris"
]]

In [16]:
arcs_arrondissements.head()

   iu_ac                  geometry  code_iris           nom_iris
0   7023  POINT (2.38368 48.89883)  751197401  Pont de Flandre 1
1   1479  POINT (2.40264 48.87834)  751197525        Amérique 25
2   1165  POINT (2.30486 48.82706)  751145603        Plaisance 3
3   1445  POINT (2.41293 48.85399)  751208009         Charonne 9
4   5198  POINT (2.28918 48.88591)  751176515          Ternes 15

In [18]:
arcs_arrondissements = (
    arcs_arrondissements[["iu_ac", "code_iris", "nom_iris"]]
    .drop_duplicates()
    .drop_duplicates(subset=["iu_ac"])
)

In [19]:
import os

output_dir = "../silver/trafic/iris/"
os.makedirs(output_dir, exist_ok=True)

chunk_size = 500_000

for i, start in enumerate(range(0, len(trafic_arcs), chunk_size)):
    chunk = trafic_arcs.iloc[start:start + chunk_size].copy()

    merged = chunk.merge(
        arcs_arrondissements,
        on="iu_ac",
        how="left",
        validate="many_to_one"
    )

    gdf_chunk = gpd.GeoDataFrame(
        merged,
        geometry="geometry",
        crs=trafic_arcs.crs
    )

    output_file = os.path.join(output_dir, f"silver_trafic_chunk_{i:03d}.parquet")
    gdf_chunk.to_parquet(output_file)

In [22]:
import pandas as pd
import geopandas as gpd
import glob

files = glob.glob("../silver/trafic/iris/*.parquet")

results = []

for f in files:
    chunk = gpd.read_parquet(f)

    agg_chunk = (
        chunk.groupby(["code_iris", "nom_iris"], as_index=False)
        .agg(
            trafic_total_q=("q", "sum"),
            trafic_moyen_q=("q", "mean"),
            occupation_moyenne_k=("k", "mean"),
            nb_mesures=("iu_ac", "count"),
            nb_arcs=("iu_ac", "nunique")
        )
    )

    results.append(agg_chunk)

gold_trafic = (
    pd.concat(results, ignore_index=True)
    .groupby(["code_iris", "nom_iris"], as_index=False)
    .agg(
        trafic_total_q=("trafic_total_q", "sum"),
        nb_mesures=("nb_mesures", "sum"),
        nb_arcs=("nb_arcs", "sum"),
        occupation_moyenne_k=("occupation_moyenne_k", "mean")
    )
)

gold_trafic["trafic_moyen_q"] = (
    gold_trafic["trafic_total_q"] / gold_trafic["nb_mesures"]
)

gold_trafic.head()

,code_iris,nom_iris,trafic_total_q,nb_mesures,nb_arcs,occupation_moyenne_k,trafic_moyen_q
0,751010101,Saint-Germain l'Auxerrois 1,6592288.0,43800,281,11.909900,150.508858
1,751010103,Saint-Germain l'Auxerrois 3,0.0,8760,60,NaN,0.000000
2,751010104,Saint-Germain l'Auxerrois 4,21356758.0,105120,624,9.451583,203.165506
3,751010105,Tuileries,3757880.0,26280,166,6.619277,142.993912
4,751010199,Seine et Berges,38081454.0,140160,778,8.630011,271.699872

In [ ]:
gold_trafic.to_parquet("../gold/trafic_iris.parquet")